### ISSUE TITLE
Doesn't go left

### ISSUE THREAD

**Issue by Leptune99** [NamelessFaceless/raubahnskip#1]
Any ideia on why does he won't go left when the "proceed" confirmation pops up?

@NamelessFaceless

**Comment by holl0wstar** [comment]
It could be a multitude of things. I've had a lot of people report the problem to me and it always came down to Numpad4 being bound to a different key, or them not being in borderless windowed.

It doesn't work outside of Borderless Windowed, and I have only tested it on 1080p - But most of my friends are on lower resolutions and have gotten it working flawlessly.

Try not blocking the window with anything, and just let the script run by itself without alt tabbing and such. This can also be a problem, since it reads your screen instead of just the game itself. Unfortunately it's an AutoHotkey limitation.

**Comment by mexcell11** [comment]
Do you know how your friends did it by any chance? I'm running 1360x768 and I cant figure it out. At some points I get close, like when It commences the duty but then it reverts back to finding the duty dialog instead of trying to skip cutscene dialog.

**Comment by Leptune99** [comment]
Yes, it was a resolution problem. I hadn't actually checked the code itself yet. Preatty neat thing you did there. Anyhow, thanks for the help.

**Comment by holl0wstar** [comment]
@Leptune99 If you managed to find a way to fix it, please let me know. I want to make sure this works for as many people as possible.

**Comment by Leptune99** [comment]
@NamelessFaceless It worked for me after I switched to borderless.
