### ISSUE TITLE
Has difficulty detecting images

### ISSUE THREAD

**Issue by felixchiasson** [NamelessFaceless/raubahnskip#2]
I'm not sure if anyone has run into this, but the script doesn't seem to be finding the duty/skip/esc windows at all. My resolution is 1080p and I am running it in borderless windowed mode. Is there something I'm missing?

Thanks!

@NamelessFaceless

**Comment by holl0wstar** [comment]
Possibly!
Can you tell me what is in the greentext when it's supposed to select the things? And, are you sure you have all the files together with the script?

Third, you could try running it as an admin.

**Comment by holl0wstar** [comment]
Also, make sure there's nothing covering the windows!

**Comment by felixchiasson** [comment]
The green text only changes from Searching for duty window when the screen is black (and it becomes In Cutscene). Let me try to run as admin.

**Comment by felixchiasson** [comment]
Alright - 

All the files are inside the same folder as the script. I ran as admin, and it did not change anything.

**Comment by holl0wstar** [comment]
Okay. This could be an entirely different issue I haven't been able to track down yet.

Can you send me a screenshot from your ESC menu and the yes/no prompt, please?

**Comment by felixchiasson** [comment]
http://imgur.com/a/2Z5Mm

Here you go

**Comment by holl0wstar** [comment]
Also, do oyu have numpad4 bound to something else?

**Comment by felixchiasson** [comment]
No, I put d-pad left to Numpad4 and Confirm to Numpad0.

**Comment by holl0wstar** [comment]
Okay, just to make sure. I'm working on a fix right now, and I'll send it over to you so you can test it.

**Comment by felixchiasson** [comment]
Sounds great, thank you :)

**Comment by holl0wstar** [comment]
I need you to download this zip file and replace the files that the download comes with, with these.
See if it works. If it doesn't, it's something on the script and I'll look more deeply into it.

https://transfer.sh/1sjYW/fix.zip

**Comment by holl0wstar** [comment]
(Unfortunately can't test these myself - I'm far past them)

**Comment by felixchiasson** [comment]
Does not work. Here's an updated screenshot:

http://imgur.com/a/DbXY1

**Comment by holl0wstar** [comment]
Must be a script problem then. Bear with me, I'm working on this, but I need you to do a few more things for me.

https://b.catgirlsare.sexy/8wl0.png

See those green dots? I need you to deactivate the script, and place the mouse over each of them. The green text will tell you coordinates, and I need the coordinates for all for.

Topleft:
Topright:
Bottomleft:
Bottomright:

Thanks for the patience, and I deeply apologize due to how troublesome this has been.

**Comment by felixchiasson** [comment]
Here's a rough estimate since the cursor becomes a hand so it's a bit hard to know exactly where the dot is

Topleft: 755 465
Topright: 836 465
Bottomleft: 755 485
Bottomright: 836 485

If you were talking about the image itself (I'm not sure whether you wanted me to do this in game or in the browser)
Topleft: 915 567
Topright: 1035 567
Bottomleft: 908 601
Bottomright: 1035 601


and honestly, no need to apologize. You're doing great work with this script. All this is nothing compared to this stupid MSQ.

**Comment by MMorikone** [comment]
Seconding, but I'm playing on borderless 3440x1440. The script brings up the duty menu and then doesn't select proceed, rather it just exits the duty window as if pressing Numpad0 again.

**Comment by holl0wstar** [comment]
The game itself! My apologies. This should give me a hand in fixing the script.

**Comment by felixchiasson** [comment]
Then yeah, the first set of coordinates should be the closest. I used the index finger as the "pointer" for when the cursor was a hand.

**Comment by MMorikone** [comment]
Topleft: 1518 651
Topright: 1612 651
Bottomleft: 1510 670
Bottomright: 1611 670

These are approximate values but the rough location where the dots are at my resolution.

**Comment by holl0wstar** [comment]
@felixchiasson Try this version of the script, just replace the old one in the folder. And bring the old images back.

https://hastebin.com/ugevujecaf.vbs

If it doesn't work, I unfortunately can't provide any more support for tonight. It's 2 am, and I need to get ready to go to bed. 

If you do find a solution while I'm sleeping, I'm all ears. I'm tempted to rewrite all of this into something easier to fix, as AHK has been unreliable to say the least.


@MMorikone Your problem seems to be a little more intricate, but I have an idea.

Try runnig this version, https://hastebin.com/nafetalocu.go

And let me know how it goes. I'll try to help as much as I can later on.

**Comment by MMorikone** [comment]
No dice! Thanks for the attempt anyways.

**Comment by felixchiasson** [comment]
Unfortunately, no dice.

I'll try to see if I can come up with something. Thanks for your help!

**Comment by holl0wstar** [comment]
You two are welcome. Unfortunately there's a lot of intricacies to the script and it's hard for me to track down all of them without having the proper way to test them.

I hope you guys can manage!

**Comment by felixchiasson** [comment]
I have managed to make the script work on my end by using colours at specific positions on the screen (like you did for the cutscene)

I took arbitrary positions to select the colour of the red text of the duty dialog and the skip dialog.
Right under PixelGetColor, color...

```
PixelGetColor, colorDuty, 905, 558
PixelGetColor, colorSkip, 758, 540
```

Then I replaced line 97 (the if clause for skipping cutscene) with
`
if colorSkip = 0x879BA0`

and line 123 with

`if colorDuty = 0x0A274E`

Unfortunately this will probably not work for 1440p, but @MMorikone if you want to give me a bit of info I might be able to make it work on your end.

**Comment by MMorikone** [comment]
@felixchiasson Sure, what do you need?

**Comment by felixchiasson** [comment]
http://imgur.com/a/dh0R6
https://gist.github.com/felixchiasson/cbd2fb7d59fb7dfbcc7f1d146d9addb0

It's probably easier if you make the changes yourself, but here's what I did.

Get an arbitrary point from both dialog windows (the green dots for example). Try to take two points that have obviously different colours and are far away from each other. Once that's done, reload and start the script and take note of the two hexadecimal numbers that appear (they start with 0x) when each window pops up.

The first number is the colorDuty and the second number is colorSkip. Replace those where mentioned in the script and things should work fine and dandy.

Obviously there is a simpler solution, but this at least makes it work for the time being.

**Comment by holl0wstar** [comment]
@felixchiasson Thanks for posting your solution! I'm going to close this issue, and direct people here if the script doesn't work and they feel they can modify/learn from this. Unfortunately, I can't do any more tests on the script since I'm far past all the quests. But I hope it's been of use for all of you. 😄
